apiVersion: app/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-app
    app: demo-result-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
  
  template:
    metadata:
      name: result-app-pod 
      labels:
        name: result-app-pod 
        app: demo-voting-app
    spec:
    containers:
      - name: result-app
      image: kodecloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80

